services:
  dotfiles-minimal:
    build:
      target: minimal
      additional_contexts:
        setupscripts: ./setup
    image: galkkk/dotfiles:minimal
    stdin_open: true
    tty: true
    volumes:
      - /:/host/
      - /var/run/docker.sock:/var/run/docker.sock
  dotfiles-full:
    build:
      target: full
      additional_contexts:
        setupscripts: ./setup
    image: galkkk/dotfiles:full
    stdin_open: true
    tty: true
    volumes:
      - /:/host/
      - /var/run/docker.sock:/var/run/docker.sock
  toolbox:
    image: galkkk/dotfiles:full
    stdin_open: true
    tty: true
    hostname: toolbox
    network_mode: host
    volumes:
      - ${HOME}:${HOME}
      - /tmp:/tmp
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: ${HOME}
    environment:
      - HOME=${HOME}
      - TERM=${TERM}
      - DISPLAY=${DISPLAY:-}
