# vim:fileencoding=utf-8:ft=conf:foldmethod=marker

# fonts {{{
# font_family Anonymous Pro
# font_family Azeret Mono
# font_family Cousine
# font_family DejaVu Sans Mono
# font_family Fira Code
# font_family IBM Plex Mono
# font_family Iosevka
# font_family Roboto Mono
# font_family Victor Mono

font_family family="Iosevka Term" style="Light"

font_size 18
modify_font cell_width 90%

#   XXXXXXXXX test that shows that kitty renders p10k symbols correctly

disable_ligatures cursor
# }}}

# scrollback {{{
scrollback_lines -1
map f1 launch --stdin-source=@screen_scrollback code -
map f2 launch --stdin-source=@screen_scrollback vim -
# }}}

# appearance {{{
window_border_width 0.0
cursor_shape beam
# subtle cursor animation
cursor_trail 3
cursor_trail_decay 0.1 0.4
# dim inactive windows
inactive_text_alpha 0.6
scrollbar scrolled
scrollbar_width 0.5
scrollbar_hover_width 1
scrollbar_handle_opacity 0.5
scrollbar_track_opacity 0
scrollbar_track_hover_opacity 0.1
tab_bar_style powerline
tab_powerline_style slanted
# }}}

# behavior {{{
shell_integration disabled
clipboard_control write-clipboard write-primary read-clipboard read-primary
confirm_os_window_close 2       # ask before closing with active processes
# never hide mouse
mouse_hide_wait -1
enable_audio_bell no
notify_on_cmd_finish invisible 10.0 notify
# }}}

# BEGIN_KITTY_THEME
# Vibrant Ink
include current-theme.conf
# END_KITTY_THEME
