name: ci

on:
  push:
    branches:
      - 'master'

concurrency:
  group: build-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push minimal image
        uses: docker/build-push-action@v4
        with:
          push: true
          target: minimal
          tags: galkkk/dotfiles:minimal
      -
        name: Build and push full image
        uses: docker/build-push-action@v4
        with:
          push: true
          target: full
          tags: galkkk/dotfiles:full
